# Generated by Django 5.1.7 on 2025-03-21 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0002_case_client"),
        ("clients", "0002_migrate_case_clients"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "State"),
                            ("local", "Local"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jurisdiction", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("e_filing_available", models.BooleanField(default=False)),
                ("e_filing_url", models.URLField(blank=True)),
                (
                    "pacer_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="PACER Court Code"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Court",
                "verbose_name_plural": "Courts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Docket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docket_number", models.CharField(max_length=100)),
                ("case_name", models.CharField(max_length=255)),
                ("date_filed", models.DateField()),
                ("date_terminated", models.DateField(blank=True, null=True)),
                (
                    "date_converted",
                    models.DateField(
                        blank=True,
                        help_text="Date when case was converted to another type",
                        null=True,
                    ),
                ),
                ("date_discharged", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Judge or official assigned to the case",
                        max_length=255,
                    ),
                ),
                (
                    "referred_to",
                    models.CharField(
                        blank=True,
                        help_text="Additional referral information",
                        max_length=255,
                    ),
                ),
                ("cause", models.CharField(blank=True, max_length=255)),
                ("nature_of_suit", models.CharField(blank=True, max_length=255)),
                ("jury_demand", models.CharField(blank=True, max_length=100)),
                ("demand", models.TextField(blank=True)),
                ("jurisdiction", models.CharField(blank=True, max_length=255)),
                (
                    "mdl_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MDL Status"
                    ),
                ),
                (
                    "federal_office_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Federal DN Office Code",
                    ),
                ),
                (
                    "federal_case_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Federal DN Case Type",
                    ),
                ),
                (
                    "federal_judge_initials_assigned",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Federal Judge Initials (Assigned)",
                    ),
                ),
                (
                    "federal_judge_initials_referred",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Federal Judge Initials (Referred)",
                    ),
                ),
                (
                    "federal_defendant_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Federal Defendant Number",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docket",
                        to="cases.case",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dockets",
                        to="docket.court",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_dockets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_dockets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Docket",
                "verbose_name_plural": "Dockets",
                "ordering": ["-date_filed"],
                "unique_together": {("court", "docket_number")},
            },
        ),
        migrations.CreateModel(
            name="DocketEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_filed", models.DateField()),
                (
                    "date_entered",
                    models.DateField(
                        help_text="Date when the entry was officially entered into the system"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Sequential or identifying number for the document",
                        max_length=50,
                    ),
                ),
                (
                    "pacer_doc_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="PACER Document ID"
                    ),
                ),
                (
                    "pacer_seq_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="PACER Sequence Number",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the docket entry"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="docket.docket",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docket_entries",
                        to="documents.document",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Docket Entry",
                "verbose_name_plural": "Docket Entries",
                "ordering": ["-date_filed", "-date_entered"],
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("plaintiff", "Plaintiff"),
                            ("defendant", "Defendant"),
                            ("debtor", "Debtor"),
                            ("creditor", "Creditor"),
                            ("trustee", "Trustee"),
                            ("us_trustee", "U.S. Trustee"),
                            ("third_party", "Third Party"),
                            ("intervenor", "Intervenor"),
                            ("petitioner", "Petitioner"),
                            ("respondent", "Respondent"),
                            ("claimant", "Claimant"),
                            ("appellant", "Appellant"),
                            ("appellee", "Appellee"),
                            ("interested_party", "Interested Party"),
                            ("mediator", "Mediator"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "extra_info",
                    models.TextField(
                        blank=True,
                        help_text="Additional details such as address or contact information",
                    ),
                ),
                ("date_terminated", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docket_appearances",
                        to="clients.client",
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="docket.docket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party",
                "verbose_name_plural": "Parties",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Attorney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "roles",
                    models.CharField(
                        blank=True, help_text="Comma-separated roles", max_length=255
                    ),
                ),
                (
                    "contact",
                    models.TextField(
                        blank=True,
                        help_text="Contact information including address, phone, email, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="docket_appearances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attorneys",
                        to="docket.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attorney",
                "verbose_name_plural": "Attorneys",
                "ordering": ["name"],
            },
        ),
    ]
