# Generated by Django 5.1.7 on 2025-03-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aws", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s3configuration",
            name="bucket_name",
            field=models.CharField(
                help_text="S3 Bucket Name - must be globally unique and follow S3 naming rules",
                max_length=255,
            ),
        ),
    ]
