# Generated by Django 5.1.7 on 2025-03-19 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aws", "0002_alter_s3configuration_bucket_name"),
    ]

    operations = []
