# Generated by Django 5.1.7 on 2025-03-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aws", "0003_auto_20250319_0410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedrockconfiguration",
            name="aws_secret_access_key",
            field=models.CharField(
                help_text="AWS Secret Access Key - keep this secure", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="bedrockconfiguration",
            name="default_model_id",
            field=models.CharField(
                default="us.anthropic.claude-3-sonnet-20240229-v1:0",
                help_text="Default model ID to use - include regional prefix (e.g., 'us.')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="s3configuration",
            name="aws_secret_access_key",
            field=models.CharField(
                help_text="AWS Secret Access Key - keep this secure", max_length=255
            ),
        ),
    ]
